services:
  netbird:
    image: netbirdio/netbird:latest
    cap_add:
      - NET_ADMIN
      - SYS_RESOURCE
    environment:
      - NB_MANAGEMENT_URL=${NB_MANAGEMENT_URL}
      - NB_SETUP_KEY=${NB_SETUP_KEY}
    volumes:
      - netbird-data:/etc/netbird
    ports:
      - "8100:8000"
    restart: unless-stopped

  app:
    network_mode: "service:netbird"
    ports: !reset []

volumes:
  netbird-data:
