from typing import Protocol


class StorageBackend(Protocol):
    async def save(self, namespace: str, image_id: str, data: bytes, ext: str) -> None: ...

    async def get(self, namespace: str, image_id: str) -> tuple[bytes, str] | None:
        """Returns (image_bytes, media_type) or None if not found."""
        ...

    async def delete_namespace(self, namespace: str) -> int: ...

    async def url(self, namespace: str, image_id: str, base_url: str) -> str: ...

    async def close(self) -> None: ...
